# Generated by Django 5.2.5 on 2025-08-12 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do produto.', max_length=200)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do produto.', null=True)),
                ('quantidade', models.IntegerField(default=0, help_text='Quantidade atual em estoque.')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, help_text='Preço unitário do produto.', max_digits=10, null=True)),
                ('data_entrada', models.DateTimeField(auto_now_add=True, help_text='Data em que o produto foi registrado.')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, help_text='Última vez que as informações do produto foram atualizadas.')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='home.empresa')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('login', models.CharField(max_length=20, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('is_admin', models.BooleanField(default=False, help_text='Indica se o usuário é administrador da empresa.')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='home.empresa')),
            ],
        ),
    ]
